### ISSUE TITLE
Crashes mobile browser

### ISSUE THREAD

**Issue by sahlstra** [andrewhodel/fiatleak#3]
Crashes Chrome on iOS7.02 as well as Safari.

**Comment by andrewhodel** [comment]
This probably boils down to the hardware when many trades come through at the same time being unable to keep up with the animation.

I may just remove the animation for mobile requests and only show the increasing numbers per currency and for BTC in a list format.  Like a quickview for mobile of fiatleak.

Any suggestions or ideas?

**Comment by Henrique-Potter** [comment]
Try grouping the "buy orders" for Bitcoin animations  and cap the number of
simultaneous Animations.

On Wed, Nov 20, 2013 at 10:43 AM, Andrew Hodel notifications@github.comwrote:

> This probably boils down to the hardware when many trades come through at
> the same time being unable to keep up with the animation.
> 
> I may just remove the animation for mobile requests and only show the
> increasing numbers per currency and for BTC in a list format. Like a
> quickview for mobile of fiatleak.
> 
> Any suggestions or ideas?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrewhodel/fiatleak/issues/3#issuecomment-28889710
> .

## 

att.,
-Henrique Pötter

**Comment by andrewhodel** [comment]
Perhaps leave all transactions > 1 BTC as a large coin, and group any transactions < 1 BTC together in 1 second groups with a icon that signifies this is a cluster of trades... this would also enable a value to be floated off with that cluster as it currently is with transactions > 1 BTC.

**Comment by Hasimir** [comment]
Try to find out from sahlstra whether the site only occasionally crashes or every single time.  A lot of things were changed in iOS 7, including javascript and HTML5 handling.

As for worrying about the power of phones and tablets, if that's really a concern then consider a language that runs server side to render the data (e.g. Python, Perl, Ruby, whatever it is you want).  Then it's just a matter of loading the images from data on the server.

**Comment by andrewhodel** [comment]
Fiatleak now simply leaves out the animations on Mobile and works as intended.

@Hasimir unfortunately there's nothing a backend can do about displaying local animations.

**Comment by sahlstra** [comment]
Sorry about the delayed response.  It was every single time, but its working fine now in both Chrome and Safari on iPhone iOS 7.0.3. Thanks for the great webapp Andrew!
