### ISSUE TITLE
Vary BTC icons continuously with size?

### ISSUE THREAD

**Issue by JimHarperDC** [andrewhodel/fiatleak#4]
This is a really fun webapp - and kinda addictive to watch. I have a couple of ideas that might make it even better. I'll treat each as a separate issue. (Please freely close them if you don't agree or if you think they're not worth the effort.)

Varying the size of the icons continuously with the size of the trades would make the visualization just a little more intuitively informative. It looks like there are two sizes, <1BTC and >1BTC. I'd love to see a whole variety.

**Comment by andrewhodel** [comment]
Right now the size is 40px if the trade is 1BTC or higher, if the trade is less than 1BTC we scale it down to a minimum of 20px.

That's not much difference, perhaps a better scaling range could be used.

Here's the current logic:

```
    var s = 40;

    if (Number(bitcoins) < 1) {
        s = s * Number(bitcoins);
    }

    if (s < 10) {
        s = 20;
    }
```

Maybe if the max size was increased to 60, and the threshold for the max size was set to 5BTC there would be a more noticeable difference in the trade size.

**Comment by andrewhodel** [comment]
I changed some things around and I think it made it much better, here's the commit:

https://github.com/andrewhodel/fiatleak/commit/109e7a0d1f4589a52e925c3a94cb35ed0add5195

Refresh the site, what do you think @JimHarperDC ?

**Comment by JimHarperDC** [comment]
Better! Thanks!
